---
spring:
  datasource:
    username: postgres
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/cache-app
  jpa:
    properties:
      hibernate: 
       dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create